traccia_1_4_Salesforce/force-app/main/default/objects/Prenotazione__c/Prenotazione__c.object-meta.xml
<CustomObject>
    <label>Prenotazione</label>
    <nameField>
        <displayFormat>PRT-{0000000}</displayFormat>
        <label>Prenotazione Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prenotazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

traccia_1_4_Salesforce/force-app/main/default/objects/Prenotazione__c/fields/data_fine__c.field-meta.xml
<CustomField>
    <fullName>data_fine__c</fullName>
    <label>Data Fine</label>
    <type>Date</type>
</CustomField>

traccia_1_4_Salesforce/force-app/main/default/objects/Prenotazione__c/fields/data_inizio__c.field-meta.xml
<CustomField>
    <fullName>data_inizio__c</fullName>
    <label>Data inizio</label>
    <type>Date</type>
</CustomField>

traccia_1_4_Salesforce/force-app/main/default/objects/Prenotazione__c/fields/metodo_pagamento__c.field-meta.xml
<CustomField>
    <fullName>metodo_pagamento__c</fullName>
    <label>Metodo pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bonifico</fullName>
            </value>
            <value>
                <fullName>Carta_di_credito</fullName>
            </value>
            <value>
                <fullName>Carta_di_debito_Bancomat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

traccia_1_4_Salesforce/force-app/main/default/objects/Prenotazione__c/fields/Stanza__c.field-meta.xml
<CustomField>
    <fullName>Stanza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stanza</label>
    <referenceTo>Stanza__c</referenceTo>
    <relationshipLabel>Prenotazioni</relationshipLabel>
    <relationshipName>Prenotazioni</relationshipName>
    <type>Lookup</type>
</CustomField>

traccia_1_4_Salesforce/force-app/main/default/objects/Prenotazione__c/fields/stato_pagamento__c.field-meta.xml
<CustomField>
    <fullName>stato_pagamento__c</fullName>
    <label>Stato pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>credito_soggiorno</fullName>
            </value>
            <value>
                <fullName>pagamento_effettuato</fullName>
            </value>
            <value>
                <fullName>in_verifica</fullName>
            </value>
            <value>
                <fullName>annullato_utente</fullName>
            </value>
            <value>
                <fullName>annullato_verifica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

traccia_1_4_Salesforce/force-app/main/default/objects/Prenotazione__c/fields/Utenza_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Utenza_Cliente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Utenza Cliente</label>
    <referenceTo>utenza_cliente__c</referenceTo>
    <relationshipLabel>Prenotazioni</relationshipLabel>
    <relationshipName>Prenotazioni</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

traccia_1_4_Salesforce/force-app/main/default/objects/Stanza__c/Stanza__c.object-meta.xml
<CustomObject>
    <label>Stanza</label>
    <nameField>
        <label>Stanza Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stanze</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

traccia_1_4_Salesforce/force-app/main/default/objects/utenza_cliente__c/utenza_cliente__c.object-meta.xml
<CustomObject>
    <label>Utenza Cliente</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utenze Clienti</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

traccia_1_4_Salesforce/force-app/main/default/classes/InsertPrenotazione.cls
@RestResource(urlMapping='/api/insert_prenotazione')
global with sharing class InsertPrenotazione {
    @HttpPost
    global static PrenotazioneDTO.InsertPrenotazioneResponseDTO creaPrenotazione() {
        try {
            // Parsing del body JSON in un oggetto DTO
            RestRequest req = RestContext.request;
            PrenotazioneDTO.InsertPrenotazioneRequestDTO requestData =
                (PrenotazioneDTO.InsertPrenotazioneRequestDTO) JSON.deserialize(req.requestBody.toString(), PrenotazioneDTO.InsertPrenotazioneRequestDTO.class);

            // Ottenere lo stato di pagamento dalla strategia
            String statoPagamento = PaymentStatusStrategyWrapper.getPaymentStatus(requestData.idMetodoPagamento);

            // Creazione della prenotazione con lo stato pagamento valorizzato
            Prenotazione__c prenotazione = new Prenotazione__c(
                Utenza_Cliente__c = requestData.idUser,
                Stanza__c = requestData.idStanza,
                Data_Inizio__c = Date.valueOf(requestData.dataInizio),
                Data_Fine__c = Date.valueOf(requestData.dataFine),
                Metodo_Pagamento__c = requestData.idMetodoPagamento,
                Stato_Pagamento__c = statoPagamento
            );
            insert prenotazione;

            // Associazione servizi
            PrenotazioneUtils.associaServiziPrenotazione(prenotazione.Id, requestData.serviziIds);

            // Creazione della risposta con il DTO
            return new PrenotazioneDTO.InsertPrenotazioneResponseDTO(true, 'Prenotazione creata con successo', prenotazione.Id);

        } catch (Exception e) {
            return new PrenotazioneDTO.InsertPrenotazioneResponseDTO(false, 'Errore durante la creazione: ' + e.getMessage(), null);
        }
    }
}