traccia_1_4_Salesforce/force-app/main/default/objects/Prenotazione__c/Prenotazione__c.object-meta.xml
<CustomObject>
    <label>Prenotazione</label>
    <nameField>
        <displayFormat>PRT-{0000000}</displayFormat>
        <label>Prenotazione Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prenotazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

traccia_1_4_Salesforce/force-app/main/default/objects/Prenotazione__c/fields/data_inizio__c.field-meta.xml
<CustomField>
    <fullName>data_inizio__c</fullName>
    <label>Data inizio</label>
    <type>Date</type>
</CustomField>

traccia_1_4_Salesforce/force-app/main/default/objects/Prenotazione__c/fields/metodo_pagamento__c.field-meta.xml
<CustomField>
    <fullName>metodo_pagamento__c</fullName>
    <label>Metodo pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bonifico</fullName>
            </value>
            <value>
                <fullName>Carta_di_credito</fullName>
            </value>
            <value>
                <fullName>Carta_di_debito_Bancomat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

traccia_1_4_Salesforce/force-app/main/default/objects/Prenotazione__c/fields/stato_pagamento__c.field-meta.xml
<CustomField>
    <fullName>stato_pagamento__c</fullName>
    <label>Stato pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>credito_soggiorno</fullName>
            </value>
            <value>
                <fullName>pagamento_effettuato</fullName>
            </value>
            <value>
                <fullName>in_verifica</fullName>
            </value>
            <value>
                <fullName>annullato_utente</fullName>
            </value>
            <value>
                <fullName>annullato_verifica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

traccia_1_4_Salesforce/force-app/main/default/objects/Prenotazione__c/fields/stato_pagamento_user_notified__c.field-meta.xml
<CustomField>
    <fullName>stato_pagamento_user_notified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>stato_pagamento_user_notified</label>
    <type>Checkbox</type>
</CustomField>

traccia_1_4_Salesforce/force-app/main/default/classes/PrenotazioneVerificaPagamentoScheduler.cls
global class PrenotazioneVerificaPagamentoScheduler implements Schedulable{
    global void execute(SchedulableContext ctx) {

        Date today = Date.today();

        // Query per ottenere le prenotazioni che rispettano i criteri
        List<Prenotazione__c> prenotazioniDaAggiornare = [
            SELECT Id, Data_Inizio__c, Metodo_Pagamento__c, Stato_Pagamento__c, Stato_Pagamento_User_Notified__c
            FROM Prenotazione__c
            WHERE 
                Data_Inizio__c >= :today
                AND Data_Inizio__c <= :today.addDays(3)
                AND Metodo_Pagamento__c = 'Bonifico'
                AND Stato_Pagamento__c = 'in_verifica'
                AND Stato_Pagamento_User_Notified__c = false
        ];

        // Aggiornamento dello stato pagamento
        if (!prenotazioniDaAggiornare.isEmpty()) {
            for (Prenotazione__c p : prenotazioniDaAggiornare) {
                p.Stato_Pagamento__c = 'Annullato_Verifica';
            }
            update prenotazioniDaAggiornare;
        }
    }
}