traccia_1_4_Salesforce/force-app/main/default/objects/Prenotazione__c/Prenotazione__c.object-meta.xml
<CustomObject>
    <label>Prenotazione</label>
    <nameField>
        <displayFormat>PRT-{0000000}</displayFormat>
        <label>Prenotazione Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prenotazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

traccia_1_4_Salesforce/force-app/main/default/objects/Prenotazione__c/fields/data_fine__c.field-meta.xml
<CustomField>
    <fullName>data_fine__c</fullName>
    <label>Data Fine</label>
    <type>Date</type>
</CustomField>

traccia_1_4_Salesforce/force-app/main/default/objects/Prenotazione__c/fields/data_inizio__c.field-meta.xml
<CustomField>
    <fullName>data_inizio__c</fullName>
    <label>Data inizio</label>
    <type>Date</type>
</CustomField>

traccia_1_4_Salesforce/force-app/main/default/classes/UpdatePrenotazione.cls
@RestResource(urlMapping='/api/update_prenotazione')
global with sharing class UpdatePrenotazione {
    @HttpPut
    global static PrenotazioneDTO.UpdatePrenotazioneResponseDTO modificaPrenotazione() {
        try {
            // Parsing del body JSON in un oggetto DTO
            RestRequest req = RestContext.request;
            PrenotazioneDTO.UpdatePrenotazioneRequestDTO requestData =
                (PrenotazioneDTO.UpdatePrenotazioneRequestDTO) JSON.deserialize(req.requestBody.toString(), PrenotazioneDTO.UpdatePrenotazioneRequestDTO.class);

            // Recupero e aggiornamento della prenotazione
            Prenotazione__c prenotazione = [SELECT Id FROM Prenotazione__c WHERE Id = :requestData.prenotazioneId LIMIT 1];
            prenotazione.Data_Inizio__c = Date.valueOf(requestData.dataInizio);
            prenotazione.Data_Fine__c = Date.valueOf(requestData.dataFine);
            update prenotazione;

            // Aggiornamento servizi
            PrenotazioneUtils.associaServiziPrenotazione(requestData.prenotazioneId, requestData.serviziIds);

            // Creazione della risposta con il DTO
            return new PrenotazioneDTO.UpdatePrenotazioneResponseDTO(true,'Prenotazione aggiornata con successo');
        } catch (Exception e) {
            return  new PrenotazioneDTO.UpdatePrenotazioneResponseDTO(false,'Errore durante la modifica: ' + e.getMessage());
        }
    }
}