traccia_1_4_Salesforce/force-app/main/default/objects/Stanza__c/Stanza__c.object-meta.xml
<CustomObject>
    <label>Stanza</label>
    <nameField>
        <label>Stanza Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stanze</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

traccia_1_4_Salesforce/force-app/main/default/objects/Stanza__c/fields/costo_per_notte__c.field-meta.xml
<CustomField>
    <fullName>costo_per_notte__c</fullName>
    <label>Costo per Notte</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

traccia_1_4_Salesforce/force-app/main/default/objects/Stanza__c/fields/descrizione__c.field-meta.xml
<CustomField>
    <fullName>descrizione__c</fullName>
    <label>descrizione</label>
    <type>TextArea</type>
</CustomField>

traccia_1_4_Salesforce/force-app/main/default/objects/Stanza__c/fields/num_letti_matrimoniali__c.field-meta.xml
<CustomField>
    <fullName>num_letti_matrimoniali__c</fullName>
    <label>Numero Letti Matrimoniali</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

traccia_1_4_Salesforce/force-app/main/default/objects/Stanza__c/fields/num_letti_singoli__c.field-meta.xml
<CustomField>
    <fullName>num_letti_singoli__c</fullName>
    <label>Numero Letti SIngoli</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

traccia_1_4_Salesforce/force-app/main/default/objects/Stanza__c/fields/tipologia_stanza__c.field-meta.xml
<CustomField>
    <fullName>tipologia_stanza__c</fullName>
    <label>tipologia stanza</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Camera_Standard</fullName>
            </value>
            <value>
                <fullName>Camera_Deluxe</fullName>
            </value>
            <value>
                <fullName>Suite_Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

traccia_1_4_Salesforce/force-app/main/default/classes/GetStanzeDisponibiliDTO.cls
public with sharing class GetStanzeDisponibiliDTO {
    public Id Id { get; set; }
    public String Nome { get; set; }
    public String Descrizione { get; set; }
    public Integer NumLettiSingoli { get; set; }
    public Integer NumLettiMatrimoniali { get; set; }
    public Integer Capacita { get; set; }
    public Decimal CostoPerNotte { get; set; }
    public Decimal CostoTotale { get; set; }
    public String TipologiaStanza { get; set; }

    // Costruttore per inizializzare i dati da un oggetto Stanza__c
    public GetStanzeDisponibiliDTO(Stanza__c stanza, Integer numeroNotti) {
        this.Id = stanza.Id;
        this.Nome = stanza.Name;
        this.Descrizione = stanza.Descrizione__c;
        this.NumLettiSingoli = (Integer)stanza.Num_Letti_Singoli__c;
        this.NumLettiMatrimoniali = (Integer)stanza.Num_Letti_Matrimoniali__c;
        this.Capacita = (Integer)stanza.Num_Letti_Singoli__c + (Integer)(stanza.Num_Letti_Matrimoniali__c * 2);
        this.CostoPerNotte = stanza.Costo_Per_Notte__c;
        this.CostoTotale = numeroNotti * stanza.Costo_Per_Notte__c;
        this.TipologiaStanza = stanza.Tipologia_Stanza__c;
    }
}